---
abstract: 'Mojolicious plugin for caching'
author:
  - 'Siddhartha Basu <biosidd@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-Cache
requires:
  CHI: 0.36
  Mojolicious: 0.999926
resources:
  repository: git://github.com/cybersiddhu/Mojolicious-Plugin-Caching.git
version: 0.0013
